#!/usr/bin/bash

cfgdir="$HOME"/OJ-Submissions-Parser/codeforces

if [[ -f "$cfgdir"/params ]]; then
  source "$cfgdir"/params
else
  exit 1
fi

# unix stamp time
time=$(date '+%s')

# 6 random digits
rand6=$(seq 9 | shuf -n 6 | xargs echo | sed "s/ //g")

# be careful. you must put the secret key and the method name at the end of the parameters file
# other parameters put them at the begining of the parameters file in any order you wish
hashed=$(printf '%s/%s?%s&time=%s#%s' "$rand6" "$method_name" "$(cat "$cfgdir"/params | sed "s/=/ /g; s/\"//g" | sed 4q | sort -h | sed "s/ /=/g" | xargs echo -n | sed "s/ /\&/g")" "$time" "$secretKey" | sha512sum | awk '{print $1}')

json=$(curl -s "https://codeforces.com/api/$method_name?handle=$handle&from=$from&count=$count&apiKey=$apiKey&time=$time&apiSig=$rand6$hashed")

echo "$json" | jq > "$cfgdir"/submissions.json
