#!/bin/bash

cfdir="$HOME"/OJ-Submissions-Parser/codeforces
spdir="$HOME"/OJ-Submissions-Parser/spoj

echo "writing README header..."
cat head.md > README.md
sleep 0.5s

echo "pulling codeforces submissions..."
cat "$cfdir"/README.md >> README.md
"$cfdir"/cfpulljson
"$cfdir"/cfsparser.py >> README.md
sleep 0.5s

echo "format spoj submissions..."
cat "$spdir"/README.md >> README.md
"$spdir"/gen_input
"$spdir"/spojparser < "$spdir"/input.in >> README.md

echo "writing README tailer..."
cat tail.md >> README.md
sleep 0.5s

echo "Done."
