#!/bin/bash

codeforcesdir="$HOME"/OJ-Submissions-Parser/codeforces

echo "pulling codeforces submissions..."
"$codeforcesdir"/cfpulljson
sleep 0.5s

echo "writing README header..."
cat "$codeforcesdir"/cfhead.md > README.md
sleep 0.5s

echo "writing submissions table..."
"$codeforcesdir"/cfsparser.py >> README.md
sleep 0.5s

echo "writing README tailer..."
cat tail.md >> README.md
sleep 0.5s

echo "Done."
