#!/bin/bash

cfdir="$HOME"/OJ-Submissions-Parser/codeforces
spdir="$HOME"/OJ-Submissions-Parser/spoj
uvadir="$HOME"/OJ-Submissions-Parser/uva-oj
atcdir="$HOME"/OJ-Submissions-Parser/atcoder

echo "writing README header..."
cat head.md > README.md

echo "parsing codeforces submissions..."
cat "$cfdir"/cfhead.md > "$cfdir"/README.md
"$cfdir"/cfjson
"$cfdir"/cfsparser.py >> "$cfdir"/README.md
cat "$cfdir"/README.md >> README.md
sleep 0.05s

echo "parsing atcoder submissions..."
cat "$atcdir"/atchead.md > "$atcdir"/README.md
"$atcdir"/atcjson
"$atcdir"/atcsparser.py >> "$atcdir"/README.md
cat "$atcdir"/README.md >> README.md
sleep 0.05s

echo "parsing uva oj submissions..."
cat "$uvadir"/uvahead.md > "$uvadir"/README.md
"$uvadir"/uvajson
"$uvadir"/uvasparser.py >> "$uvadir"/README.md
cd "$uvadir"/solutions
"$uvadir"/solutions/generate_files
cd ../../
cat "$uvadir"/README.md >> README.md
sed -i "s|(uva\-oj\/|(|g" "$uvadir"/README.md
sleep 0.05s

echo "parsing spoj submissions..."
cat "$spdir"/spojhead.md > "$spdir"/README.md
"$spdir"/geninput
"$spdir"/spojsparser < "$spdir"/input.in >> "$spdir"/README.md
cat "$spdir"/README.md >> README.md
sed -i "s/(spoj\//(/g" "$spdir"/README.md
sleep 0.05s

echo "writing README tailer..."
cat tail.md >> README.md
sleep 0.05s

echo "Done."
